language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"

env:
  - TOXENV=py

jobs:
  include:
    - env: TOXENV=lint

cache: pip

before_install:
  - pip install -U pip
install:
  - pip install -U codecov tox

script:
  - python setup.py test

after_success:
  - codecov

branches:
  only:
    - master
